language: python
python:
  - "3.6"
before_install:
  - python --version
  - pip install -U pip
  - pip install -U wheel
  - pip install -U pytest
install:
  - pip install numpy
  - pip install scipy
  - pip install matplotlib
  - pip install ".[test]" . # install package + test dependencies (blog.travis-ci.com/2019-08-07-extensive-python-testing-on-travis-ci
# command to run tests
script:
  - pytest --cov-report=xml --cov=newt newt\tests\